- src/engine/Core.java
- src/engine/DrawManager.java
- src/screen/TitleScreen.java
only make 2p mode mutton (not some,, 2player mode game screen or something)
> create 2p player mode button

- src/engine/Core.java
- src/engine/DrawManager.java
- src/engine/GameState_2P.java
- src/screen/EnhanceScreen_2P.java
- src/screen/GameScreen_2P.java
- src/screen/RandomBoxScreen_2P.java
- src/screen/RandomRewardScreen_2P.java
- src/screen/RecoveryPaymentScreen_2P.java
- src/screen/StoreScreen_2P.java
- src/screen/SubMenuScreen_2P.java
- src/screen/TwoPlayScoreScreen.java
- connect currency, item related screen to 2 player mode
- develop some currency, item screen fit to 2 player mode
- develop connection between 2 player object to coin, item, enemy
- add coin HUD
- add EnhanceManager and ItemManger to 2P screen
> feat: connect currency, item screens to 2 player mode

- Database/create_invaders_table.sql
Added sql file containing invader database schema.
The table consists of three parts: player, score, and rank.
> Database table Schema Design

- .gitignore
- src/Database/create_invaders_table.sql
- src/engine/Core.java
- src/engine/DrawManager.java
- src/engine/Login.java
- src/screen/AuthManageScreen.java
- src/screen/LoginScreen.java
- src/screen/RegisterScreen.java
1. Edit Login logic
2. Implement Register logic
3. Implement AuthManage(Register/Login) Screen
> Implement about AuthManage

- res/Database/V1__Client.sql
- Create about Client table schema
> :card_file_box: SDP-33 Create Client.sql

- src/engine/LoginManager.java
> :sparkles: SDP-36 add Login Manager

- src/engine/DatabaseConnect.java
- src/engine/RegisterManager.java
> :sparkles: SDP-35 add Register engine

- res/Database/V2__Score.sql
- res/Database/V3__Ranking.sql
> 🗃️ SDP-43 Create Ranking.sql

- src/engine/ScoreManager.java
> :sparkles: SDP-48 ScoreManager.java: add score into database

- src/engine/LoginManager.java
> :hammer: Sdp 36 implement login feature

- src/engine/DatabaseConnect.java
- src/engine/RegisterManager.java
- Create Database connect
- Create Register manager
> 🔨 SDP-35 implement register feature

- config/pmd/ruleset.xml
* Ruleset contents added
* changing Ruleset order
> SDP-60-CI-Testing

- .gitignore
- src/engine/Core.java
- src/engine/DatabaseConnect.java
- src/engine/DrawManager.java
- src/engine/LoginManager.java
- src/screen/GameScreen.java
- src/screen/LoginScreen.java
- src/screen/TitleScreen.java
Connect Login engine with new method Login Screen
> :sparkles: Sdp 37 implement login screen

- src/engine/Core.java
- src/engine/LoginManager.java
- src/engine/RegisterManager.java
- src/screen/LoginScreen.java
- src/screen/RegisterScreen.java
Change some management code to connect with register screen
Add register screen for sign up
> ✨ Sdp 38 implement register screen

- res/Database/V1__Client.sql
- res/Database/V4__Friend_List.sql
- res/Database/V5__is_online.sql
- src/screen/LoginScreen.java
- Create is_online.sql
- Update about online value
- Update is_online value upon login
> 🗃️ 🔨 SDP-53 Update about user online status

- src/engine/FriendManager.java
new function return friend data
> SDP-57 implement freind management engine

- .env
- README.md
- build.gradle
- src/engine/DatabaseConnect.java
- Deploy database
- Update README.md (java version dependency)
> 🚀 SDP-70 deployment database

- src/engine/Core.java
- src/engine/InputManager.java
- src/engine/LoginManager.java
- src/engine/RegisterManager.java
- src/screen/LoginScreen.java
- src/screen/TitleScreen.java
hotfix about LoginScreen / Mangaer
> :ambulance: Hotfix about LoginScreen and manager

- src/engine/DrawManager.java
- src/engine/ScoreManager.java
- src/screen/ScoreMenuScreen.java
Fix some score screen menu to connect our new database
> :sparkles: To connect new score screen with our database, fix some code

- build.gradle
- ADD database driver dependency on build.gradle
> 🚑 Hotfix about database

- src/engine/Core.java
- src/engine/DrawManager.java
- src/engine/LoginManager.java
- src/screen/HighScoreScreen.java
- src/screen/LoginScreen.java
- src/screen/PersonalScoreScreen.java
Uncompleted Score screen, only for connect
> :lipstick: SDP-45 Add PersonalScoreScreen

- src/engine/Core.java
- src/engine/DrawManager.java
- src/engine/LoginManager.java
- src/engine/RegisterManager.java
- src/screen/GameScreen.java
- src/screen/LoginScreen.java
- src/screen/RegisterScreen.java
Change some code about connect with screens and manager
FIx about Issues #61
> :ambulance: Issues #61 Critical bug about Login / Register Screen

- src/engine/Core.java
- src/engine/DatabaseConnect.java
- src/engine/DrawManager.java
- src/engine/ScoreManager.java
- src/screen/PersonalScoreScreen.java
- src/screen/ScoreScreen.java
Personalscore Screen that show logined id's scores
> :sparkles: SDP-45 Devleopment about personalscore screen

- src/engine/Core.java
- src/screen/GlobalScoreScreen.java
Global Score Screen show about all user's ranking. connect that screen in invaders
> :sparkles: SDP-46 implement global ranking screen

- src/screen/LoginScreen.java
- src/screen/RegisterScreen.java
- src/security/SHA256.java
- Set up sha-256 encryption to the password.
> :lock: SDP-72 Set up user security

- res/Database/V3__Ranking.sql
- src/engine/Core.java
- src/screen/CountryScoreScreen.java
Connect Country Score Screen with our database.
This is a screen that displays the ranking and score among people from the same country.
> :sparkles: SDP-47 Devleopment about Country Score Screen

- src/engine/Core.java
- src/engine/DrawManager.java
- src/engine/FriendManager.java
- src/screen/CountryScoreScreen.java
- src/screen/FriendAddScreen.java
- src/screen/FriendDeleteScreen.java
- src/screen/FriendListScreen.java
- src/screen/FriendMenuScreen.java
- src/screen/GlobalScoreScreen.java
- src/screen/PersonalScoreScreen.java
- src/screen/TitleScreen.java
If you receive an ID as input, you can add or delete friends. Up to 5 people are allowed.
> ✨ SDP-56 Add Friend Add, Delete Frame

- build.gradle
- Add dependency about JAR file
> :ambulance: Hotfix about JAR file dependency
